### ISSUE TITLE
This text area shoud be a a simple reply-text instead of reply-subtitle

### ISSUE THREAD

**Issue by fredmarques** [calamar-io/controltower#85]
Setting this as `reply-subtitle` saves it as a subtitle inside dynamo instead of text. Bot doesn't know how to answer then.
(inspect Resposta -> answer's text bubble to reproduce image)
![textarea](https://cloud.githubusercontent.com/assets/8461400/19532034/be8a0b92-9618-11e6-91a4-d0efb6005ddc.png)

**Comment by fczuardi** [comment]
reply-subtitle is just the css classname in the screenshot above, what writes subtitles on dynamo should be something else…

**Comment by fczuardi** [comment]
the problem is probably here: https://github.com/calamar-io/controltower/blob/master/src/components/replyListForm.js#L53

the name filed should be name='subtitle' only for answers of template type 'generic' and name='text' otherwise.

I can submit a fix for that.

**Comment by fczuardi** [comment]
probably not related, but white testing this bug I've found another one #86
