### ISSUE TITLE
Relicense under the MIT License

### ISSUE THREAD

**Issue by fczuardi** [calamar-io/controltower#94]
In order to be more flexible for commercial scenarios with this code mixing with closed/proprietary code, we are considering to re-license this project under a permissive [MIT License](https://opensource.org/licenses/MIT)

For this, we need the permission of all authors/committers, (they are listed in the [AUTHORS](https://github.com/calamar-io/controltower/blob/master/AUTHORS) file).

If your name is there, please reply in this issue saying "I give you permission to re-license controltower under MIT License".

Thanks!

**Comment by fczuardi** [comment]
cc @fredmarques @gnardari

**Comment by fredmarques** [comment]
I give you permission to re-license controltower under MIT License

**Comment by gnardari** [comment]
I give you permission to re-license controltower under MIT License
